version: 2.1
jobs:
  test_percy:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn --ignore-engines
      - run:
          name: Install selenium-webdriver
          command: yarn add selenium-webdriver@3.6.0
      - run:
          name: Run Percy Tests
          command: yarn test
  test:
    docker:
      - image: circleci/node:12-browsers
    environment:
      PERCY_ENABLE: 0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: npx semantic-release
workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test
      - test_percy
      - release:
          requires:
            - test
            - test_percy
